ALTER TABLE books ADD COLUMN gutendex_id BIGINT UNIQUE NULL;
ALTER TABLE books ADD COLUMN download_url LONGTEXT NULL;
ALTER TABLE books ADD COLUMN cover_url LONGTEXT NULL;
ALTER TABLE books ADD COLUMN languages LONGTEXT NULL;
ALTER TABLE books ADD COLUMN subjects LONGTEXT NULL;
ALTER TABLE books ADD COLUMN download_count INT NULL;

ALTER TABLE books MODIFY COLUMN publisher_id BIGINT NULL;

ALTER TABLE books DROP INDEX title;
ALTER TABLE books MODIFY COLUMN title VARCHAR(255) NOT NULL;

ALTER TABLE books DROP COLUMN genre;

CREATE INDEX idx_gutendex_id ON books(gutendex_id);

