apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    pvc: pvc-alexandria
  name: data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: alexandria
