apiVersion: v1
kind: Secret
metadata:
  name: core-secrets
  namespace: alexandria
type: Opaque
stringData:
  mysql-password: alexandria123
  mysql-root-password: alexandria123
  jwt-secret: dev-secret-key-not-for-production-min-256bits
  callback-secret: "troque-me-callback"
