sonar.projectKey=mba-puc-alexandria_alexandria
sonar.organization=mba-puc-alexandria

sonar.sources=src
sonar.exclusions=**/target/**,**/*.java.orig

sonar.javascript.lcov.reportPaths=coverage/lcov.info