name: TruffleHog Scan Test

on: 
  pull_request:
    branches:
      - main

jobs:
  truffehog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up TruffleHog
      run: | 
            docker pull  trufflesecurity/trufflehog:latest

    - name: Run TruffleHog
      run: |
            
            docker run --rm -it -v "$PWD:/" trufflesecurity/trufflehog:latest github --org=mba-puc-alexandria
